### ISSUE TITLE
Two new points.  One pending.

### ISSUE THREAD

**Issue by exlibris** [tap-map/tap-map.github.io#7]
{
      "type": "Feature",
      "properties": {
        "title": "The Stone Saloon",
        "address": "445 Smith Avenue North",
        "web": " http://www.stonesaloon.com/",
        "status": "pending",
        "expected": "2017"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -93.109444,
          44.938333
        ]
      }
    },

{
      "type": "Feature",
      "properties": {
        "title": "The Freeehouse",
        "address": "701 N Washington Ave #101",
        "web": "www.freehousempls.com/",
        "status": "open”
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -93.299332,
          44.953833
        ]
      }
    },

**Comment by fawcett** [comment]
Freehouse added.  Thank you for your support!
